WebBomba/ViewComponents/UserLinkViewComponent.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WebBomba.Data.Entities.Identity;
using WebBomba.Models.Account;

namespace WebBomba.ViewComponents;

public class UserLinkViewComponent : ViewComponent
{
    private readonly UserManager<UserEntity> _userManager;

    public UserLinkViewComponent(UserManager<UserEntity> userManager)
    {
        _userManager = userManager;
    }
    public IViewComponentResult Invoke()
    {
        var userName = User.Identity?.Name;
        var model = new UserLinkViewModel();
        if (userName != null)
        {
            var user = _userManager.FindByEmailAsync(userName).Result;
            model.Image = user.Image;
            model.Name = $"{user.LastName} {user.FirstName}";
        }

        // Pass the model to the view
        return View(model);
    }
}

WebBomba/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebBomba</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebBomba.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebBomba</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WebBomba - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebBomba/Views/Shared/_SiteHeader.cshtml
<header>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <div class="container">
            <a class="navbar-brand" href="/">Головна</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/Product">Продукти</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link disabled">Disabled</a>
                    </li>
                </ul>
                @if (User.Identity.IsAuthenticated)
                {
                    <ul class="navbar-nav">
                        @await Component.InvokeAsync("UserLink")
                        <li class="nav-item">
                            @using (Html.BeginForm("Logout", "Account", FormMethod.Post))
                            {
                                <button class="nav-link btn btn-link">Вихід</button>
                            }
                        </li>
                    </ul>
                }
                else
                {
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" asp-action="Login" asp-controller="Account">Вхід</a>
                        </li>
                    </ul>
                }
            </div>
        </div>
    </nav>
</header>

WebBomba/Views/Shared/_SiteLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Категорії</title>
    <link href="/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet"/>
    <link href="/css/site.css" rel="stylesheet"/>
</head>
<body>

@await Html.PartialAsync("_SiteHeader")

<div class="container">
    @RenderBody()
</div>

<script src="/lib/bootstrap/dist/js/bootstrap.min.js"></script>

@await RenderSectionAsync("Scripts", required: false)
</body>
</html>